In [ ]:
x = np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
print(np.zeros(20))
print(np.zeros(10, dtype='int32'))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]


In [ ]:
x1=np.array([[1,2],[2,3],[3,4]])
print(x1)
print(np.zeros((3,4)))


[[1 2]
 [2 3]
 [3 4]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
print(np.ones(10))
print(np.ones(10,dtype='int64'))
print(np.ones((2,3,4)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
print(np.full((4,3),15))

[[15 15 15]
 [15 15 15]
 [15 15 15]
 [15 15 15]]


In [ ]:
print(np.arange(10,5,-2))
print(np.arange(10))
print(np.arange(1,11))

[10  8  6]
[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(np.arange(1,13).reshape(4,3))


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
print(np.linspace(1,10,5))
print(np.linspace(0,1,5))

[ 1.    3.25  5.5   7.75 10.  ]
[0.   0.25 0.5  0.75 1.  ]


In [ ]:
print(np.eye(4))
print(np.eye(3,4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [ ]:
print(np.eye(3,4,k=2))


[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [ ]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(np.arange(20,1,-2))

[20 18 16 14 12 10  8  6  4  2]


In [ ]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
arr = np.arange(16).reshape(4,4)
print(arr)
print("matShape:", arr.shape)
print("matSize:", arr.size)
print("matDim:", arr.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
matShape: (4, 4)
matSize: 16
matDim: 2


In [ ]:
arr=np.arange(10)
print(arr)
print(arr[-3])
print(arr[-3:-12:-2])

[0 1 2 3 4 5 6 7 8 9]
7
[7 5 3 1]


In [ ]:
arr=np.arange(12).reshape(3,4)
print(arr)
print(arr[2,2])
print(arr[::2,::3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
10
[[ 0  3]
 [ 8 11]]


In [ ]:
print(arr[1:,2:])


[[ 6  7]
 [10 11]]


In [ ]:
print(arr[1,1:])

[5 6 7]


In [ ]:
print(arr[0, 0], arr[0, -1], arr[-1, 0], arr[-1, -1])

0 3 8 11
[[ 0  1  2  3]
 [ 8  9 10 11]]


[6 5 4]
[10  9  8]


In [ ]:
print(arr[1, 2::-1])
print(arr[2, 2::-1])