In [1]:
import numpy as np


In [6]:
mark = np.array([35,68,42,91,27,55])
print(np.where(mark>50))
print(np.where(mark>50, 'pass', 'fail'))

(array([1, 3, 5]),)
['fail' 'pass' 'fail' 'pass' 'fail' 'pass']


In [9]:
import numpy as np

In [16]:
marks = np.array([92,61,45,78,33,55])
grades = np.where(marks > 75, 'A',
         np.where(marks > 50, 'B', 'C'))

print(grades)
grades = np.where(marks >=50, 'B',
         np.where(marks >=75, 'A', 'C'))
print(grades)



['A' 'B' 'C' 'A' 'C' 'B']
['B' 'B' 'C' 'B' 'C' 'B']


In [17]:
a = np.array([1,2,3])
b =np.array([4,5,6])
print(np.dot(a,b))
print(a@b)

32
32


In [22]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[3,5],[5,6],[7,8]])
print(x)
print(x.T)
print(np.dot(x,y))
print(y.T)


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[34 41]
 [79 98]]
[[3 5 7]
 [5 6 8]]


In [5]:
s1 = [72, 85, 60, 91]
s2 = [45, 30, 98, 55]
s3 =[88, 66, 74, 100]
old = np.array([
    ['62', '71', '55', '80'],
    ['49','58','66','73']
    ])
table = np.array([s1, s2, s3]) #1
print(table)
print(f" no of students {table.shape[0]} and no. of subjects {table.shape[1]}") #2#3

print(table.size)#4
decimal_number = table.astype(float)#5
print(decimal_number)
old = old.astype('int32')#6
print(np.sum(old, axis=0))#7
print(np.sum(old, axis =1))#7
print(table.astype(float))#8
print(np.vstack((table, old)))


[[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]]
 no of students 3 and no. of subjects 4
12
[[ 72.  85.  60.  91.]
 [ 45.  30.  98.  55.]
 [ 88.  66.  74. 100.]]
[111 129 121 153]
[268 246]
[[ 72.  85.  60.  91.]
 [ 45.  30.  98.  55.]
 [ 88.  66.  74. 100.]]
[[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]
 [ 62  71  55  80]
 [ 49  58  66  73]]


In [2]:
import numpy as np

In [3]:
marks = np.zeros((6,4)) #1
print(marks)
marks = np.full((6,4), 35) #2
print(marks)
std = np.arange(101,131,2) #3
print(std)
time = np.linspace(0,3,7) #4
print(time)
arr = np.eye(5, dtype=int)*10 #6
print(arr)
table = np.full((4, 4), 35) #7
np.fill_diagonal(table, 100)
print(table)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]]
[101 103 105 107 109 111 113 115 117 119 121 123 125 127 129]
[0.  0.5 1.  1.5 2.  2.5 3. ]
[[10  0  0  0  0]
 [ 0 10  0  0  0]
 [ 0  0 10  0  0]
 [ 0  0  0 10  0]
 [ 0  0  0  0 10]]
[[100  35  35  35]
 [ 35 100  35  35]
 [ 35  35 100  35]
 [ 35  35  35 100]]
